import Survival.KSATChernoffCollapse
import Survival.NAESATChernoffCollapse
import Survival.XORSATChernoffCollapse
import Survival.QColoringChernoffCollapse
import Survival.ForbiddenPatternCSPChernoffCollapse
import Survival.MultiForbiddenPatternCSP
import Survival.HypergraphColoringChernoffCollapse
import Survival.CardinalitySATChernoffCollapse
import Survival.ThresholdCardinalitySATChernoffCollapse
import Survival.ExactlyOneSATChernoffCollapse

/-!
# Bernoulli CSP Universality Interface

This module freezes the common interface shared by the Bernoulli bad-event CSP
instances currently formalized in the development:

* random `k`-SAT fixed-assignment clause exposure;
* random `k`-NAE-SAT fixed-assignment clause exposure;
* random `k`-XOR-SAT fixed-assignment equation exposure;
* fixed-coloring `q`-coloring edge exposure;
* generic finite-alphabet forbidden-pattern exposure;
* multi-forbidden-pattern witness exposure;
* fixed-coloring `q`-coloring `k`-uniform hyperedge exposure.
* fixed-assignment exactly-`r`-of-`k` cardinality-SAT exposure via a
  multi-forbidden witness;
* fixed-assignment at-most-`r` and at-least-`r` threshold cardinality-SAT
  exposure via multi-forbidden witnesses;
* fixed-assignment exactly-one-SAT exposure via a multi-forbidden witness.

The point is not to add a new concentration proof.  The point is to make the
common template explicit: once a domain supplies a Bernoulli bad-event
probability in `(0, 1)`, the existing path-measure, MGF-product,
Chernoff/KL-profile, collapse, stopped-collapse, and hitting-time wrappers are
available uniformly.
-/

namespace Survival.BernoulliCSPUniversality

open MeasureTheory
open ProbabilityTheory
open Survival.BernoulliCSPTemplate
open Survival.BernoulliCSPPathMeasure
open Survival.BernoulliCSPPathChernoff
open Survival.BernoulliCSPPathCollapse
open Survival.HighProbabilityCollapse
open Survival.StoppingTimeHighProbabilityCollapse
open Survival.StoppingTimeCollapseEvent

noncomputable section

/-- A domain-facing Bernoulli bad-event CSP instance.  All downstream
finite-horizon probability and collapse structure is generated from the single
`Parameters` field. -/
structure ExposureModel where
  parameters : Parameters

namespace ExposureModel

/-- Bad-event probability of an exposure model. -/
def badProb (M : ExposureModel) : ℝ :=
  M.parameters.badProb

theorem badProb_pos (M : ExposureModel) :
    0 < M.badProb :=
  M.parameters.badProb_pos

theorem badProb_lt_one (M : ExposureModel) :
    M.badProb < 1 :=
  M.parameters.badProb_lt_one

/-- Mean one-step information-production drift. -/
def drift (M : ExposureModel) : ℝ :=
  M.parameters.drift

theorem drift_pos (M : ExposureModel) :
    0 < M.drift :=
  M.parameters.drift_pos

/-- One-sided bad-event emission scale. -/
def badEmissionScale (M : ExposureModel) : ℝ :=
  M.parameters.badEmissionScale

theorem expectedBadEmission_eq_drift (M : ExposureModel) :
    M.badProb * M.badEmissionScale = M.drift :=
  M.parameters.expectedBadEmission_eq_drift

/-- Finite-horizon iid Bernoulli bad-event path PMF. -/
def pathPMF (M : ExposureModel) (N : ℕ) :
    PMF (Trajectory N) :=
  BernoulliCSPPathMeasure.pathPMF M.parameters N

/-- Finite-horizon iid Bernoulli bad-event path measure. -/
def pathMeasure (M : ExposureModel) (N : ℕ) :
    Measure (Trajectory N) :=
  BernoulliCSPPathMeasure.pathMeasure M.parameters N

instance instIsProbabilityMeasurePathMeasure (M : ExposureModel) (N : ℕ) :
    IsProbabilityMeasure (M.pathMeasure N) := by
  dsimp [pathMeasure]
  infer_instance

/-- Real-valued bad-count random variable on the active prefix. -/
def badCountRV (M : ExposureModel) (N n : ℕ) :
    Trajectory N → ℝ :=
  BernoulliCSPPathMeasure.badCountRV M.parameters N n

/-- Uniform MGF product law generated by the actual finite path PMF. -/
theorem mgf_badCountRV_eq_bernoulliBadMGF_pow
    (M : ExposureModel) (N : ℕ) (t : ℝ) :
    ∀ ⦃n : ℕ⦄, n ≤ N + 1 →
      mgf (M.badCountRV N n) (M.pathMeasure N) t =
        bernoulliBadMGF M.badProb t ^ n := by
  intro n hn
  exact
    BernoulliCSPPathMeasure.mgf_badCountRV_eq_bernoulliBadMGF_pow
      M.parameters N t hn

/-- KL/Chernoff failure profile attached to the exposure model. -/
def countChernoffFailureBound (M : ExposureModel) :
    CountFailureProfile :=
  M.parameters.chernoffFailureBound

/-- Exact lower-tail failure profile on the actual path measure. -/
def exactCountFailureBound (M : ExposureModel)
    (N n : ℕ) (r : ℝ) : ENNReal :=
  BernoulliCSPPathChernoff.exactCountFailureBound
    M.parameters N n r

/-- Interior KL/Chernoff count-tail bound, uniformly for every exposure model. -/
theorem exactCountFailureBound_le_chernoffFailureBound_of_interior
    (M : ExposureModel) (N : ℕ) {n : ℕ} (hn : n ≤ N + 1) {r : ℝ}
    (hr : 0 ≤ r)
    (hlt : r < (n : ℝ) * M.drift) :
    M.exactCountFailureBound N n r ≤
      M.countChernoffFailureBound n r := by
  exact
    BernoulliCSPPathChernoff.exactCountFailureBound_le_chernoffFailureBound_of_interior
      M.parameters N hn hr (by simpa [drift] using hlt)

/-- Uniform cumulative-production process for the exposure model. -/
def process (M : ExposureModel) (N : ℕ) (s₀ : ℝ) :=
  BernoulliCSPPathCollapse.process M.parameters N s₀

/-- Uniform fixed-time collapse wrapper. -/
theorem collapseWithChernoffBound_of_linearMargin
    (M : ExposureModel) (N : ℕ) {n : ℕ} (hn : n ≤ N + 1)
    {s₀ θ r : ℝ}
    (hr : 0 ≤ r)
    (hlt : r < (n : ℝ) * M.drift)
    (hθ : 0 < θ)
    (hmargin :
      -Real.log θ ≤
        BernoulliCSPPathChernoff.linearCenter M.parameters s₀ n - r) :
    CollapseWithFailureBound
      (μ := M.pathMeasure N)
      (M.process N s₀)
      n θ
      (M.countChernoffFailureBound n r) := by
  exact
    BernoulliCSPPathCollapse.collapseWithChernoffBound_of_linearMargin
      M.parameters N hn hr (by simpa [drift] using hlt) hθ hmargin

/-- Uniform stopped-collapse wrapper. -/
theorem stoppedCollapseWithChernoffBound_of_linearMargin
    (M : ExposureModel) (N : ℕ) {T : ℕ} (hT : T ≤ N + 1)
    {s₀ θ r : ℝ}
    (hr : 0 ≤ r)
    (hlt : r < (T : ℝ) * M.drift)
    (hθ : 0 < θ)
    (hmargin :
      -Real.log θ ≤
        BernoulliCSPPathChernoff.linearCenter M.parameters s₀ T - r) :
    StoppedCollapseWithFailureBound
      (μ := M.pathMeasure N)
      (M.process N s₀)
      T θ
      (M.countChernoffFailureBound T r) := by
  exact
    BernoulliCSPPathCollapse.stoppedCollapseWithChernoffBound_of_linearMargin
      M.parameters N hT hr (by simpa [drift] using hlt) hθ hmargin

/-- Uniform hitting-time-before-horizon wrapper. -/
theorem hittingTimeBeforeHorizonWithChernoffBound_of_linearMargin
    (M : ExposureModel) (N : ℕ) {j T : ℕ} (hjT : j < T)
    (hj : j ≤ N + 1) {s₀ θ r : ℝ}
    (hr : 0 ≤ r)
    (hlt : r < (j : ℝ) * M.drift)
    (hmargin :
      -Real.log θ ≤
        BernoulliCSPPathChernoff.linearCenter M.parameters s₀ j - r) :
    HittingTimeBeforeHorizonWithFailureBound
      (μ := M.pathMeasure N)
      (M.process N s₀)
      T θ
      (M.countChernoffFailureBound j r) := by
  exact
    BernoulliCSPPathCollapse.hittingTimeBeforeHorizonWithChernoffBound_of_linearMargin
      M.parameters N hjT hj hr (by simpa [drift] using hlt) hmargin

end ExposureModel

/-- Random `k`-SAT as a Bernoulli bad-event CSP exposure model. -/
def kSAT (k : ℕ) (hk : 0 < k) : ExposureModel where
  parameters := Survival.KSATBernoulliTemplate.kSATParameters k hk

/-- Random `k`-NAE-SAT as a Bernoulli bad-event CSP exposure model. -/
def naeSAT (k : ℕ) (hk : 1 < k) : ExposureModel where
  parameters := Survival.NAESATBernoulliTemplate.naeSATParameters k hk

/-- Fixed-assignment random `k`-XOR-SAT as a Bernoulli bad-event CSP exposure
model. -/
def xorSAT (k : ℕ) : ExposureModel where
  parameters := Survival.XORSATBernoulliTemplate.xorSATParameters k

/-- Fixed-coloring `q`-coloring edge exposure as a Bernoulli bad-event CSP
exposure model. -/
def qColoring (q : ℝ) (hq : 1 < q) : ExposureModel where
  parameters := Survival.QColoringBernoulliTemplate.qColoringParameters q hq

/-- Generic finite-alphabet forbidden-pattern CSP exposure model. -/
def forbiddenPattern
    (alphabet forbidden : ℝ) (arity : ℕ)
    (ha : 0 < alphabet) (hf : 0 < forbidden)
    (hforb : forbidden < alphabet ^ arity) : ExposureModel where
  parameters :=
    Survival.ForbiddenPatternCSPTemplate.forbiddenPatternParameters
      alphabet forbidden arity ha hf hforb

/-- A multi-forbidden-pattern domain witness as a Bernoulli bad-event CSP
exposure model. -/
def multiForbiddenPattern
    (W : Survival.MultiForbiddenPatternCSP.Witness) : ExposureModel where
  parameters := W.parameters

/-- Fixed-assignment random exactly-one-SAT clause exposure as a
multi-forbidden-pattern Bernoulli bad-event CSP exposure model. -/
def exactlyOneSAT (k : ℕ) (hk : 0 < k) : ExposureModel where
  parameters :=
    Survival.ExactlyOneSATChernoffCollapse.exactlyOneSATParameters k hk

/-- Fixed-assignment random exactly-`r`-of-`k` cardinality-SAT clause exposure
as a multi-forbidden-pattern Bernoulli bad-event CSP exposure model. -/
def exactRSAT (k r : ℕ) (hk : 0 < k) (hrk : r ≤ k) : ExposureModel where
  parameters :=
    Survival.CardinalitySATChernoffCollapse.exactRSATParameters k r hk hrk

/-- Fixed-assignment random at-most-`r`-of-`k` threshold cardinality-SAT clause
exposure as a Bernoulli bad-event CSP exposure model. -/
def atMostRSAT (k r : ℕ) (hrk : r < k) : ExposureModel where
  parameters :=
    Survival.ThresholdCardinalitySATChernoffCollapse.atMostRSATParameters
      k r hrk

/-- Fixed-assignment random at-least-`r`-of-`k` threshold cardinality-SAT clause
exposure as a Bernoulli bad-event CSP exposure model. -/
def atLeastRSAT (k r : ℕ) (hrpos : 0 < r) (hrk : r ≤ k) :
    ExposureModel where
  parameters :=
    Survival.ThresholdCardinalitySATChernoffCollapse.atLeastRSATParameters
      k r hrpos hrk

/-- Fixed-coloring `q`-coloring exposure of `k`-uniform hyperedges as a
Bernoulli bad-event CSP exposure model. -/
def hypergraphColoring
    (q : ℝ) (arity : ℕ) (hq : 1 < q) (harity : 1 < arity) :
    ExposureModel where
  parameters :=
    Survival.HypergraphColoringChernoffCollapse.hypergraphColoringParameters
      q arity hq harity

theorem kSAT_badProb (k : ℕ) (hk : 0 < k) :
    (kSAT k hk).badProb =
      Survival.KSATBernoulliTemplate.kSATBadProb k :=
  rfl

theorem naeSAT_badProb (k : ℕ) (hk : 1 < k) :
    (naeSAT k hk).badProb =
      Survival.NAESATBernoulliTemplate.naeSATBadProb k :=
  rfl

theorem xorSAT_badProb (k : ℕ) :
    (xorSAT k).badProb =
      Survival.XORSATBernoulliTemplate.xorSATBadProb k :=
  rfl

theorem qColoring_badProb (q : ℝ) (hq : 1 < q) :
    (qColoring q hq).badProb =
      Survival.QColoringBernoulliTemplate.qColoringBadProb q :=
  rfl

theorem forbiddenPattern_badProb
    (alphabet forbidden : ℝ) (arity : ℕ)
    (ha : 0 < alphabet) (hf : 0 < forbidden)
    (hforb : forbidden < alphabet ^ arity) :
    (forbiddenPattern alphabet forbidden arity ha hf hforb).badProb =
      Survival.ForbiddenPatternCSPTemplate.forbiddenPatternBadProb
        alphabet forbidden arity :=
  rfl

theorem multiForbiddenPattern_badProb
    (W : Survival.MultiForbiddenPatternCSP.Witness) :
    (multiForbiddenPattern W).badProb = W.badProb :=
  rfl

theorem exactlyOneSAT_badProb (k : ℕ) (hk : 0 < k) :
    (exactlyOneSAT k hk).badProb =
      Survival.ExactlyOneSATChernoffCollapse.exactlyOneSATBadProb k :=
  rfl

theorem exactRSAT_badProb (k r : ℕ) (hk : 0 < k) (hrk : r ≤ k) :
    (exactRSAT k r hk hrk).badProb =
      Survival.CardinalitySATChernoffCollapse.exactRSATBadProb k r :=
  rfl

theorem atMostRSAT_badProb (k r : ℕ) (hrk : r < k) :
    (atMostRSAT k r hrk).badProb =
      Survival.ThresholdCardinalitySATChernoffCollapse.atMostRSATBadProb k r :=
  rfl

theorem atLeastRSAT_badProb
    (k r : ℕ) (hrpos : 0 < r) (hrk : r ≤ k) :
    (atLeastRSAT k r hrpos hrk).badProb =
      Survival.ThresholdCardinalitySATChernoffCollapse.atLeastRSATBadProb
        k r :=
  rfl

theorem hypergraphColoring_badProb
    (q : ℝ) (arity : ℕ) (hq : 1 < q) (harity : 1 < arity) :
    (hypergraphColoring q arity hq harity).badProb =
      Survival.HypergraphColoringChernoffCollapse.hypergraphColoringBadProb
        q arity :=
  rfl

theorem kSAT_drift_eq (k : ℕ) (hk : 0 < k) :
    (kSAT k hk).drift =
      Survival.KSATBernoulliTemplate.kSATDrift k hk :=
  rfl

theorem naeSAT_drift_eq (k : ℕ) (hk : 1 < k) :
    (naeSAT k hk).drift =
      Survival.NAESATBernoulliTemplate.naeSATDrift k hk :=
  rfl

theorem xorSAT_drift_eq_log_two (k : ℕ) :
    (xorSAT k).drift = Real.log 2 := by
  exact Survival.XORSATBernoulliTemplate.xorSATDrift_eq_log_two k

theorem qColoring_drift_eq_log_ratio {q : ℝ} (hq : 1 < q) :
    (qColoring q hq).drift = Real.log (q / (q - 1)) := by
  exact Survival.QColoringBernoulliTemplate.qColoringDrift_eq_log_ratio hq

theorem forbiddenPattern_drift_eq_log_ratio
    {alphabet forbidden : ℝ} {arity : ℕ}
    (ha : 0 < alphabet) (hf : 0 < forbidden)
    (hforb : forbidden < alphabet ^ arity) :
    (forbiddenPattern alphabet forbidden arity ha hf hforb).drift =
      Real.log (alphabet ^ arity / (alphabet ^ arity - forbidden)) := by
  exact
    Survival.ForbiddenPatternCSPTemplate.forbiddenPatternDrift_eq_log_ratio
      ha hf hforb

theorem multiForbiddenPattern_drift_eq_log_ratio
    (W : Survival.MultiForbiddenPatternCSP.Witness) :
    (multiForbiddenPattern W).drift =
      Real.log (W.totalPatternCount / (W.totalPatternCount - W.forbiddenCount)) := by
  exact W.drift_eq_log_ratio

theorem exactlyOneSAT_drift_eq_log_ratio
    (k : ℕ) (hk : 0 < k) :
    (exactlyOneSAT k hk).drift =
      Real.log
        (Survival.ExactlyOneSATChernoffCollapse.totalPatternCount k /
          Survival.ExactlyOneSATChernoffCollapse.allowedPatternCount k) := by
  exact
    Survival.ExactlyOneSATChernoffCollapse.exactlyOneSATDrift_eq_log_ratio
      k hk

theorem exactRSAT_drift_eq_log_ratio
    (k r : ℕ) (hk : 0 < k) (hrk : r ≤ k) :
    (exactRSAT k r hk hrk).drift =
      Real.log
        (Survival.CardinalitySATChernoffCollapse.totalPatternCount k /
          Survival.CardinalitySATChernoffCollapse.allowedPatternCount k r) := by
  exact
    Survival.CardinalitySATChernoffCollapse.exactRSATDrift_eq_log_ratio
      k r hk hrk

theorem atMostRSAT_drift_eq_log_ratio
    (k r : ℕ) (hrk : r < k) :
    (atMostRSAT k r hrk).drift =
      Real.log
        (Survival.ThresholdCardinalitySATChernoffCollapse.totalPatternCount k /
          Survival.ThresholdCardinalitySATChernoffCollapse.atMostAllowedPatternCount
            k r) := by
  exact
    Survival.ThresholdCardinalitySATChernoffCollapse.atMostRSATDrift_eq_log_ratio
      k r hrk

theorem atLeastRSAT_drift_eq_log_ratio
    (k r : ℕ) (hrpos : 0 < r) (hrk : r ≤ k) :
    (atLeastRSAT k r hrpos hrk).drift =
      Real.log
        (Survival.ThresholdCardinalitySATChernoffCollapse.totalPatternCount k /
          Survival.ThresholdCardinalitySATChernoffCollapse.atLeastAllowedPatternCount
            k r) := by
  exact
    Survival.ThresholdCardinalitySATChernoffCollapse.atLeastRSATDrift_eq_log_ratio
      k r hrpos hrk

theorem hypergraphColoring_drift_eq_log_ratio
    {q : ℝ} {arity : ℕ} (hq : 1 < q) (harity : 1 < arity) :
    (hypergraphColoring q arity hq harity).drift =
      Real.log (q ^ arity / (q ^ arity - q)) := by
  exact
    Survival.HypergraphColoringChernoffCollapse.hypergraphColoringDrift_eq_log_ratio
      hq harity

theorem hypergraphColoring_eq_multiForbiddenPattern
    (q : ℝ) (arity : ℕ) (hq : 1 < q) (harity : 1 < arity) :
    hypergraphColoring q arity hq harity =
      multiForbiddenPattern
        (Survival.HypergraphColoringChernoffCollapse.hypergraphColoringWitness
          q arity hq harity) := rfl

theorem exactlyOneSAT_eq_multiForbiddenPattern
    (k : ℕ) (hk : 0 < k) :
    exactlyOneSAT k hk =
      multiForbiddenPattern
        (Survival.ExactlyOneSATChernoffCollapse.exactlyOneSATWitness k hk) := rfl

theorem exactRSAT_eq_multiForbiddenPattern
    (k r : ℕ) (hk : 0 < k) (hrk : r ≤ k) :
    exactRSAT k r hk hrk =
      multiForbiddenPattern
        (Survival.CardinalitySATChernoffCollapse.exactRSATWitness
          k r hk hrk) := rfl

theorem atMostRSAT_eq_multiForbiddenPattern
    (k r : ℕ) (hrk : r < k) :
    atMostRSAT k r hrk =
      multiForbiddenPattern
        (Survival.ThresholdCardinalitySATChernoffCollapse.atMostRSATWitness
          k r hrk) := rfl

theorem atLeastRSAT_eq_multiForbiddenPattern
    (k r : ℕ) (hrpos : 0 < r) (hrk : r ≤ k) :
    atLeastRSAT k r hrpos hrk =
      multiForbiddenPattern
        (Survival.ThresholdCardinalitySATChernoffCollapse.atLeastRSATWitness
          k r hrpos hrk) := rfl

theorem exactlyOneSAT_eq_exactRSAT
    (k : ℕ) (hk : 0 < k) :
    exactlyOneSAT k hk =
      exactRSAT k 1 hk (Nat.succ_le_iff.mpr hk) := by
  unfold exactlyOneSAT exactRSAT
  simp [
    Survival.ExactlyOneSATChernoffCollapse.exactlyOneSATParameters,
    Survival.CardinalitySATChernoffCollapse.exactRSATParameters,
    Survival.ExactlyOneSATChernoffCollapse.exactlyOneSATWitness,
    Survival.CardinalitySATChernoffCollapse.exactRSATWitness,
    Survival.ExactlyOneSATChernoffCollapse.forbiddenPatternCount,
    Survival.CardinalitySATChernoffCollapse.forbiddenPatternCount,
    Survival.ExactlyOneSATChernoffCollapse.totalPatternCount,
    Survival.CardinalitySATChernoffCollapse.totalPatternCount,
    Survival.ExactlyOneSATChernoffCollapse.allowedPatternCount,
    Survival.CardinalitySATChernoffCollapse.allowedPatternCount,
    Nat.choose_one_right,
  ]

end

end Survival.BernoulliCSPUniversality
