import Mathlib.Data.Nat.Choose.Bounds
import Survival.MultiForbiddenPatternCSP

/-!
# Cardinality-SAT as a Multi-Forbidden-Pattern CSP

This module packages fixed-assignment random cardinality constraints as a
domain witness for the generic multi-forbidden-pattern CSP interface.

For a random signed `k`-clause, the local truth pattern has `2^k` possible
outcomes.  An exactly-`r` cardinality constraint allows the `choose k r`
patterns in which exactly `r` literals are true and forbids the remaining
`2^k - choose k r` patterns.  Therefore the bad-event probability is

`(2^k - choose k r) / 2^k`,

and the corresponding information-production drift is

`log (2^k / choose k r)`.

The scope is the same finite-horizon iid bad-event exposure layer as the other
Bernoulli-CSP instances.  It does not model solver dynamics or overlapping
constraint dependence.
-/

namespace Survival.CardinalitySATChernoffCollapse

open MeasureTheory
open Survival.BernoulliCSPTemplate
open Survival.BernoulliCSPPathMeasure
open Survival.BernoulliCSPPathChernoff
open Survival.BernoulliCSPPathCollapse
open Survival.MultiForbiddenPatternCSP
open Survival.HighProbabilityCollapse
open Survival.StoppingTimeHighProbabilityCollapse
open Survival.StoppingTimeCollapseEvent

noncomputable section

/-- Number of local truth patterns in a signed `k`-clause. -/
def totalPatternCount (k : ℕ) : ℝ :=
  (2 : ℝ) ^ k

/-- Number of local truth patterns with exactly `r` true literals. -/
def allowedPatternCount (k r : ℕ) : ℝ :=
  (k.choose r : ℝ)

/-- The exactly-one case is the `r = 1` specialization of cardinality-SAT. -/
theorem allowedPatternCount_one (k : ℕ) :
    allowedPatternCount k 1 = (k : ℝ) := by
  simp [allowedPatternCount, Nat.choose_one_right]

/-- Number of local truth patterns that violate the exactly-`r` constraint. -/
def forbiddenPatternCount (k r : ℕ) : ℝ :=
  totalPatternCount k - allowedPatternCount k r

/-- Forbidden local patterns for exactly-one are `2^k - k`. -/
theorem forbiddenPatternCount_one (k : ℕ) :
    forbiddenPatternCount k 1 = totalPatternCount k - (k : ℝ) := by
  simp [forbiddenPatternCount, allowedPatternCount_one]

theorem allowedPatternCount_pos {k r : ℕ} (hrk : r ≤ k) :
    0 < allowedPatternCount k r := by
  unfold allowedPatternCount
  exact_mod_cast (Nat.choose_pos hrk)

theorem allowedPatternCount_lt_totalPatternCount
    (k r : ℕ) (hk : 0 < k) :
    allowedPatternCount k r < totalPatternCount k := by
  unfold allowedPatternCount totalPatternCount
  exact_mod_cast (Nat.choose_lt_two_pow k r hk)

theorem forbiddenPatternCount_pos
    (k r : ℕ) (hk : 0 < k) :
    0 < forbiddenPatternCount k r := by
  unfold forbiddenPatternCount
  exact sub_pos.mpr (allowedPatternCount_lt_totalPatternCount k r hk)

theorem forbiddenPatternCount_lt_totalPatternCount
    {k r : ℕ} (hrk : r ≤ k) :
    forbiddenPatternCount k r < totalPatternCount k := by
  unfold forbiddenPatternCount totalPatternCount allowedPatternCount
  have hchoose : (0 : ℝ) < (k.choose r : ℝ) := by
    exact_mod_cast (Nat.choose_pos hrk)
  linarith

/-- Domain witness for fixed-assignment random signed exactly-`r`-of-`k`
constraint exposure. -/
def exactRSATWitness (k r : ℕ) (hk : 0 < k) (hrk : r ≤ k) :
    Witness where
  alphabet := 2
  arity := k
  forbiddenCount := forbiddenPatternCount k r
  alphabet_pos := by norm_num
  forbiddenCount_pos := forbiddenPatternCount_pos k r hk
  forbiddenCount_lt_total := by
    simpa [totalPatternCount] using forbiddenPatternCount_lt_totalPatternCount hrk

/-- Bernoulli-CSP parameters generated by the exactly-`r` witness. -/
def exactRSATParameters (k r : ℕ) (hk : 0 < k) (hrk : r ≤ k) :
    Parameters :=
  (exactRSATWitness k r hk hrk).parameters

/-- Bad-event probability for fixed-assignment exactly-`r`-of-`k` exposure. -/
def exactRSATBadProb (k r : ℕ) : ℝ :=
  forbiddenPatternCount k r / totalPatternCount k

theorem exactRSATParameters_badProb
    (k r : ℕ) (hk : 0 < k) (hrk : r ≤ k) :
    (exactRSATParameters k r hk hrk).badProb = exactRSATBadProb k r := rfl

/-- Mean one-step information-production drift for exactly-`r`-of-`k`
exposure. -/
def exactRSATDrift (k r : ℕ) (hk : 0 < k) (hrk : r ≤ k) : ℝ :=
  (exactRSATWitness k r hk hrk).drift

theorem exactRSATDrift_eq_log_ratio
    (k r : ℕ) (hk : 0 < k) (hrk : r ≤ k) :
    exactRSATDrift k r hk hrk =
      Real.log (totalPatternCount k / allowedPatternCount k r) := by
  rw [exactRSATDrift, (exactRSATWitness k r hk hrk).drift_eq_log_ratio]
  congr 2
  simp [
    exactRSATWitness,
    Witness.totalPatternCount,
    forbiddenPatternCount,
    totalPatternCount,
    allowedPatternCount,
  ]

theorem exactRSATDrift_pos
    (k r : ℕ) (hk : 0 < k) (hrk : r ≤ k) :
    0 < exactRSATDrift k r hk hrk :=
  (exactRSATWitness k r hk hrk).drift_pos

/-- Exactly-`r`-of-`k` Chernoff/KL count failure profile. -/
def countChernoffFailureBound
    (k r : ℕ) (hk : 0 < k) (hrk : r ≤ k) :
    CountFailureProfile :=
  (exactRSATWitness k r hk hrk).countChernoffFailureBound

/-- Exactly-`r`-of-`k` finite-horizon iid path measure. -/
def pathMeasure
    (k r : ℕ) (hk : 0 < k) (hrk : r ≤ k) (N : ℕ) :
    Measure (Trajectory N) :=
  (exactRSATWitness k r hk hrk).pathMeasure N

instance instIsProbabilityMeasurePathMeasure
    (k r : ℕ) (hk : 0 < k) (hrk : r ≤ k) (N : ℕ) :
    IsProbabilityMeasure (pathMeasure k r hk hrk N) := by
  dsimp [pathMeasure]
  infer_instance

/-- Cumulative-production process induced by the exactly-`r` witness. -/
def process (k r : ℕ) (hk : 0 < k) (hrk : r ≤ k) (N : ℕ) (s₀ : ℝ) :=
  (exactRSATWitness k r hk hrk).process N s₀

/-- Fixed-time collapse for exactly-`r`-of-`k` under the KL/Chernoff failure
profile. -/
theorem collapseWithChernoffBound_of_linearMargin
    (k r : ℕ) (hk : 0 < k) (hrk : r ≤ k)
    (N : ℕ) {n : ℕ} (hn : n ≤ N + 1)
    {s₀ θ margin : ℝ}
    (hmargin_nonneg : 0 ≤ margin)
    (hlt : margin < (n : ℝ) * exactRSATDrift k r hk hrk)
    (hθ : 0 < θ)
    (hthreshold :
      -Real.log θ ≤
        BernoulliCSPPathChernoff.linearCenter
          (exactRSATParameters k r hk hrk) s₀ n - margin) :
    CollapseWithFailureBound
      (μ := pathMeasure k r hk hrk N)
      (process k r hk hrk N s₀)
      n θ
      (countChernoffFailureBound k r hk hrk n margin) := by
  simpa [
    pathMeasure,
    process,
    countChernoffFailureBound,
    exactRSATParameters,
    exactRSATDrift,
  ] using
    (exactRSATWitness k r hk hrk).collapseWithChernoffBound_of_linearMargin
      N hn hmargin_nonneg (by simpa [exactRSATDrift] using hlt) hθ hthreshold

/-- Terminal stopped-collapse for exactly-`r`-of-`k` under the KL/Chernoff
failure profile. -/
theorem stoppedCollapseWithChernoffBound_of_linearMargin
    (k r : ℕ) (hk : 0 < k) (hrk : r ≤ k)
    (N : ℕ) {T : ℕ} (hT : T ≤ N + 1)
    {s₀ θ margin : ℝ}
    (hmargin_nonneg : 0 ≤ margin)
    (hlt : margin < (T : ℝ) * exactRSATDrift k r hk hrk)
    (hθ : 0 < θ)
    (hthreshold :
      -Real.log θ ≤
        BernoulliCSPPathChernoff.linearCenter
          (exactRSATParameters k r hk hrk) s₀ T - margin) :
    StoppedCollapseWithFailureBound
      (μ := pathMeasure k r hk hrk N)
      (process k r hk hrk N s₀)
      T θ
      (countChernoffFailureBound k r hk hrk T margin) := by
  simpa [
    pathMeasure,
    process,
    countChernoffFailureBound,
    exactRSATParameters,
    exactRSATDrift,
  ] using
    (exactRSATWitness k r hk hrk).stoppedCollapseWithChernoffBound_of_linearMargin
      N hT hmargin_nonneg (by simpa [exactRSATDrift] using hlt) hθ hthreshold

/-- Earlier threshold crossing gives a high-probability
hitting-time-before-horizon bound for exactly-`r`-of-`k`. -/
theorem hittingTimeBeforeHorizonWithChernoffBound_of_linearMargin
    (k r : ℕ) (hk : 0 < k) (hrk : r ≤ k)
    (N : ℕ) {j T : ℕ} (hjT : j < T)
    (hj : j ≤ N + 1) {s₀ θ margin : ℝ}
    (hmargin_nonneg : 0 ≤ margin)
    (hlt : margin < (j : ℝ) * exactRSATDrift k r hk hrk)
    (hthreshold :
      -Real.log θ ≤
        BernoulliCSPPathChernoff.linearCenter
          (exactRSATParameters k r hk hrk) s₀ j - margin) :
    HittingTimeBeforeHorizonWithFailureBound
      (μ := pathMeasure k r hk hrk N)
      (process k r hk hrk N s₀)
      T θ
      (countChernoffFailureBound k r hk hrk j margin) := by
  simpa [
    pathMeasure,
    process,
    countChernoffFailureBound,
    exactRSATParameters,
    exactRSATDrift,
  ] using
    (exactRSATWitness k r hk hrk).hittingTimeBeforeHorizonWithChernoffBound_of_linearMargin
      N hjT hj hmargin_nonneg (by simpa [exactRSATDrift] using hlt) hthreshold

end

end Survival.CardinalitySATChernoffCollapse
