import Survival.ForbiddenPatternCSPChernoffCollapse

/-!
# Multi-Forbidden-Pattern CSP Witness Layer

This module separates the domain-combinatorial witness from the generic
finite-alphabet forbidden-pattern exposure interface.

The previous forbidden-pattern layer accepts a real number `forbidden`.  This
module packages the intended domain input as a witness:

* a finite local alphabet size;
* a constraint arity;
* a positive count of forbidden local patterns;
* the proof that this count is strictly smaller than all local patterns.

Once such a witness is supplied, the existing Bernoulli-CSP path measure,
Chernoff/KL profile, and collapse wrappers are generated without reproving the
probability layer.
-/

namespace Survival.MultiForbiddenPatternCSP

open MeasureTheory
open ProbabilityTheory
open Survival.BernoulliCSPTemplate
open Survival.BernoulliCSPPathMeasure
open Survival.BernoulliCSPPathChernoff
open Survival.BernoulliCSPPathCollapse
open Survival.ForbiddenPatternCSPTemplate
open Survival.HighProbabilityCollapse
open Survival.StoppingTimeHighProbabilityCollapse
open Survival.StoppingTimeCollapseEvent

noncomputable section

/-- Domain-combinatorial witness for a finite-alphabet CSP with multiple
forbidden local patterns. -/
structure Witness where
  alphabet : ℝ
  arity : ℕ
  forbiddenCount : ℝ
  alphabet_pos : 0 < alphabet
  forbiddenCount_pos : 0 < forbiddenCount
  forbiddenCount_lt_total : forbiddenCount < alphabet ^ arity

namespace Witness

/-- Total number of local patterns represented at the witness layer. -/
def totalPatternCount (W : Witness) : ℝ :=
  W.alphabet ^ W.arity

/-- Bad-event probability generated by the domain witness. -/
def badProb (W : Witness) : ℝ :=
  forbiddenPatternBadProb W.alphabet W.forbiddenCount W.arity

/-- Bernoulli-CSP parameters generated by the domain witness. -/
def parameters (W : Witness) : Parameters :=
  forbiddenPatternParameters W.alphabet W.forbiddenCount W.arity
    W.alphabet_pos W.forbiddenCount_pos W.forbiddenCount_lt_total

theorem parameters_badProb (W : Witness) :
    W.parameters.badProb = W.badProb := rfl

theorem badProb_pos (W : Witness) :
    0 < W.badProb := by
  simpa [badProb] using W.parameters.badProb_pos

theorem badProb_lt_one (W : Witness) :
    W.badProb < 1 := by
  simpa [badProb] using W.parameters.badProb_lt_one

/-- Mean one-step information-production drift generated by the witness. -/
def drift (W : Witness) : ℝ :=
  W.parameters.drift

theorem drift_eq_log_ratio (W : Witness) :
    W.drift =
      Real.log (W.totalPatternCount / (W.totalPatternCount - W.forbiddenCount)) := by
  simpa [drift, parameters, totalPatternCount] using
    forbiddenPatternDrift_eq_log_ratio
      W.alphabet_pos W.forbiddenCount_pos W.forbiddenCount_lt_total

theorem drift_pos (W : Witness) :
    0 < W.drift :=
  W.parameters.drift_pos

/-- One-sided bad-pattern emission scale generated by the witness. -/
def badEmissionScale (W : Witness) : ℝ :=
  W.parameters.badEmissionScale

theorem badEmissionScale_pos (W : Witness) :
    0 < W.badEmissionScale :=
  W.parameters.badEmissionScale_pos

theorem expectedBadEmission_eq_drift (W : Witness) :
    W.badProb * W.badEmissionScale = W.drift :=
  W.parameters.expectedBadEmission_eq_drift

/-- Finite-horizon iid good/bad path PMF generated from the witness. -/
def pathPMF (W : Witness) (N : ℕ) : PMF (Trajectory N) :=
  BernoulliCSPPathMeasure.pathPMF W.parameters N

/-- Finite-horizon iid good/bad path measure generated from the witness. -/
def pathMeasure (W : Witness) (N : ℕ) : Measure (Trajectory N) :=
  BernoulliCSPPathMeasure.pathMeasure W.parameters N

instance instIsProbabilityMeasurePathMeasure (W : Witness) (N : ℕ) :
    IsProbabilityMeasure (W.pathMeasure N) := by
  dsimp [pathMeasure]
  infer_instance

/-- Real-valued bad-count random variable on an active prefix. -/
def badCountRV (W : Witness) (N n : ℕ) : Trajectory N → ℝ :=
  BernoulliCSPPathMeasure.badCountRV W.parameters N n

/-- MGF product law inherited from the generic Bernoulli path measure. -/
theorem mgf_badCountRV_eq_bernoulliBadMGF_pow
    (W : Witness) (N : ℕ) (t : ℝ) :
    ∀ ⦃n : ℕ⦄, n ≤ N + 1 →
      mgf (W.badCountRV N n) (W.pathMeasure N) t =
        bernoulliBadMGF W.badProb t ^ n := by
  intro n hn
  simpa [badCountRV, pathMeasure, badProb, parameters] using
    BernoulliCSPPathMeasure.mgf_badCountRV_eq_bernoulliBadMGF_pow
      W.parameters N t hn

/-- KL/Chernoff failure profile attached to the witness. -/
def countChernoffFailureBound (W : Witness) : CountFailureProfile :=
  W.parameters.chernoffFailureBound

/-- Exact lower-tail failure profile on the actual path measure. -/
def exactCountFailureBound (W : Witness) (N n : ℕ) (r : ℝ) : ENNReal :=
  BernoulliCSPPathChernoff.exactCountFailureBound W.parameters N n r

/-- Interior KL/Chernoff count-tail bound generated by the witness. -/
theorem exactCountFailureBound_le_chernoffFailureBound_of_interior
    (W : Witness) (N : ℕ) {n : ℕ} (hn : n ≤ N + 1) {r : ℝ}
    (hr : 0 ≤ r)
    (hlt : r < (n : ℝ) * W.drift) :
    W.exactCountFailureBound N n r ≤ W.countChernoffFailureBound n r := by
  exact
    BernoulliCSPPathChernoff.exactCountFailureBound_le_chernoffFailureBound_of_interior
      W.parameters N hn hr (by simpa [drift] using hlt)

/-- Cumulative-production process generated by the witness. -/
def process (W : Witness) (N : ℕ) (s₀ : ℝ) :=
  BernoulliCSPPathCollapse.process W.parameters N s₀

/-- Fixed-time collapse wrapper generated by the witness. -/
theorem collapseWithChernoffBound_of_linearMargin
    (W : Witness) (N : ℕ) {n : ℕ} (hn : n ≤ N + 1)
    {s₀ θ r : ℝ}
    (hr : 0 ≤ r)
    (hlt : r < (n : ℝ) * W.drift)
    (hθ : 0 < θ)
    (hmargin :
      -Real.log θ ≤
        BernoulliCSPPathChernoff.linearCenter W.parameters s₀ n - r) :
    CollapseWithFailureBound
      (μ := W.pathMeasure N)
      (W.process N s₀)
      n θ
      (W.countChernoffFailureBound n r) := by
  exact
    BernoulliCSPPathCollapse.collapseWithChernoffBound_of_linearMargin
      W.parameters N hn hr (by simpa [drift] using hlt) hθ hmargin

/-- Terminal stopped-collapse wrapper generated by the witness. -/
theorem stoppedCollapseWithChernoffBound_of_linearMargin
    (W : Witness) (N : ℕ) {T : ℕ} (hT : T ≤ N + 1)
    {s₀ θ r : ℝ}
    (hr : 0 ≤ r)
    (hlt : r < (T : ℝ) * W.drift)
    (hθ : 0 < θ)
    (hmargin :
      -Real.log θ ≤
        BernoulliCSPPathChernoff.linearCenter W.parameters s₀ T - r) :
    StoppedCollapseWithFailureBound
      (μ := W.pathMeasure N)
      (W.process N s₀)
      T θ
      (W.countChernoffFailureBound T r) := by
  exact
    BernoulliCSPPathCollapse.stoppedCollapseWithChernoffBound_of_linearMargin
      W.parameters N hT hr (by simpa [drift] using hlt) hθ hmargin

/-- Hitting-time-before-horizon wrapper generated by the witness. -/
theorem hittingTimeBeforeHorizonWithChernoffBound_of_linearMargin
    (W : Witness) (N : ℕ) {j T : ℕ} (hjT : j < T)
    (hj : j ≤ N + 1) {s₀ θ r : ℝ}
    (hr : 0 ≤ r)
    (hlt : r < (j : ℝ) * W.drift)
    (hmargin :
      -Real.log θ ≤
        BernoulliCSPPathChernoff.linearCenter W.parameters s₀ j - r) :
    HittingTimeBeforeHorizonWithFailureBound
      (μ := W.pathMeasure N)
      (W.process N s₀)
      T θ
      (W.countChernoffFailureBound j r) := by
  exact
    BernoulliCSPPathCollapse.hittingTimeBeforeHorizonWithChernoffBound_of_linearMargin
      W.parameters N hjT hj hr (by simpa [drift] using hlt) hmargin

end Witness

end

end Survival.MultiForbiddenPatternCSP
