import Survival.MultiForbiddenPatternCSP

/-!
# Exactly-One-SAT as a Multi-Forbidden-Pattern CSP

This module gives a thin witness-based specialization of the generic
multi-forbidden-pattern CSP interface.

For a fixed assignment and a random signed `k`-clause, the induced truth pattern
has `2^k` possible local patterns.  Exactly-one-SAT allows the `k` patterns in
which exactly one literal is true, and forbids the remaining `2^k - k`
patterns.  Therefore the bad-event probability is

`(2^k - k) / 2^k`,

and the corresponding drift is

`log (2^k / k)`.

The scope is the same finite-horizon iid bad-event exposure layer as the other
Bernoulli-CSP instances.  It does not model solver dynamics or overlapping
clause dependence.
-/

namespace Survival.ExactlyOneSATChernoffCollapse

open MeasureTheory
open Survival.BernoulliCSPTemplate
open Survival.BernoulliCSPPathMeasure
open Survival.BernoulliCSPPathChernoff
open Survival.BernoulliCSPPathCollapse
open Survival.MultiForbiddenPatternCSP
open Survival.HighProbabilityCollapse
open Survival.StoppingTimeHighProbabilityCollapse
open Survival.StoppingTimeCollapseEvent

noncomputable section

/-- Number of local truth patterns in a signed `k`-clause. -/
def totalPatternCount (k : ℕ) : ℝ :=
  (2 : ℝ) ^ k

/-- Number of local truth patterns that satisfy exactly-one. -/
def allowedPatternCount (k : ℕ) : ℝ :=
  (k : ℝ)

/-- Number of local truth patterns that violate exactly-one. -/
def forbiddenPatternCount (k : ℕ) : ℝ :=
  totalPatternCount k - allowedPatternCount k

theorem allowedPatternCount_pos {k : ℕ} (hk : 0 < k) :
    0 < allowedPatternCount k := by
  unfold allowedPatternCount
  exact_mod_cast hk

theorem allowedPatternCount_lt_totalPatternCount (k : ℕ) :
    allowedPatternCount k < totalPatternCount k := by
  unfold allowedPatternCount totalPatternCount
  exact_mod_cast (Nat.lt_two_pow_self (n := k))

theorem forbiddenPatternCount_pos (k : ℕ) :
    0 < forbiddenPatternCount k := by
  unfold forbiddenPatternCount
  exact sub_pos.mpr (allowedPatternCount_lt_totalPatternCount k)

theorem forbiddenPatternCount_lt_totalPatternCount {k : ℕ} (hk : 0 < k) :
    forbiddenPatternCount k < totalPatternCount k := by
  unfold forbiddenPatternCount totalPatternCount allowedPatternCount
  have hkreal : (0 : ℝ) < k := by exact_mod_cast hk
  linarith

/-- Domain witness for fixed-assignment random signed exactly-one `k`-clause
exposure. -/
def exactlyOneSATWitness (k : ℕ) (hk : 0 < k) : Witness where
  alphabet := 2
  arity := k
  forbiddenCount := forbiddenPatternCount k
  alphabet_pos := by norm_num
  forbiddenCount_pos := forbiddenPatternCount_pos k
  forbiddenCount_lt_total := by
    simpa [totalPatternCount] using forbiddenPatternCount_lt_totalPatternCount hk

/-- Bernoulli-CSP parameters generated by the exactly-one-SAT witness. -/
def exactlyOneSATParameters (k : ℕ) (hk : 0 < k) : Parameters :=
  (exactlyOneSATWitness k hk).parameters

/-- Bad-event probability for fixed-assignment exactly-one-SAT exposure. -/
def exactlyOneSATBadProb (k : ℕ) : ℝ :=
  forbiddenPatternCount k / totalPatternCount k

theorem exactlyOneSATParameters_badProb (k : ℕ) (hk : 0 < k) :
    (exactlyOneSATParameters k hk).badProb = exactlyOneSATBadProb k := rfl

/-- Mean one-step information-production drift for exactly-one-SAT exposure. -/
def exactlyOneSATDrift (k : ℕ) (hk : 0 < k) : ℝ :=
  (exactlyOneSATWitness k hk).drift

theorem exactlyOneSATDrift_eq_log_ratio
    (k : ℕ) (hk : 0 < k) :
    exactlyOneSATDrift k hk = Real.log (totalPatternCount k / allowedPatternCount k) := by
  rw [exactlyOneSATDrift, (exactlyOneSATWitness k hk).drift_eq_log_ratio]
  congr 2
  simp [
    exactlyOneSATWitness,
    Witness.totalPatternCount,
    forbiddenPatternCount,
    totalPatternCount,
    allowedPatternCount,
  ]

theorem exactlyOneSATDrift_pos (k : ℕ) (hk : 0 < k) :
    0 < exactlyOneSATDrift k hk :=
  (exactlyOneSATWitness k hk).drift_pos

/-- Exactly-one-SAT Chernoff/KL count failure profile. -/
def countChernoffFailureBound (k : ℕ) (hk : 0 < k) :
    CountFailureProfile :=
  (exactlyOneSATWitness k hk).countChernoffFailureBound

/-- Exactly-one-SAT finite-horizon iid path measure. -/
def pathMeasure (k : ℕ) (hk : 0 < k) (N : ℕ) :
    Measure (Trajectory N) :=
  (exactlyOneSATWitness k hk).pathMeasure N

instance instIsProbabilityMeasurePathMeasure (k : ℕ) (hk : 0 < k) (N : ℕ) :
    IsProbabilityMeasure (pathMeasure k hk N) := by
  dsimp [pathMeasure]
  infer_instance

/-- Cumulative-production process induced by the exactly-one-SAT witness. -/
def process (k : ℕ) (hk : 0 < k) (N : ℕ) (s₀ : ℝ) :=
  (exactlyOneSATWitness k hk).process N s₀

/-- Fixed-time collapse for exactly-one-SAT under the KL/Chernoff failure
profile. -/
theorem collapseWithChernoffBound_of_linearMargin
    (k : ℕ) (hk : 0 < k) (N : ℕ) {n : ℕ} (hn : n ≤ N + 1)
    {s₀ θ r : ℝ}
    (hr : 0 ≤ r)
    (hlt : r < (n : ℝ) * exactlyOneSATDrift k hk)
    (hθ : 0 < θ)
    (hmargin :
      -Real.log θ ≤
        BernoulliCSPPathChernoff.linearCenter
          (exactlyOneSATParameters k hk) s₀ n - r) :
    CollapseWithFailureBound
      (μ := pathMeasure k hk N)
      (process k hk N s₀)
      n θ
      (countChernoffFailureBound k hk n r) := by
  simpa [
    pathMeasure,
    process,
    countChernoffFailureBound,
    exactlyOneSATParameters,
    exactlyOneSATDrift,
  ] using
    (exactlyOneSATWitness k hk).collapseWithChernoffBound_of_linearMargin
      N hn hr (by simpa [exactlyOneSATDrift] using hlt) hθ hmargin

/-- Terminal stopped-collapse for exactly-one-SAT under the KL/Chernoff failure
profile. -/
theorem stoppedCollapseWithChernoffBound_of_linearMargin
    (k : ℕ) (hk : 0 < k) (N : ℕ) {T : ℕ} (hT : T ≤ N + 1)
    {s₀ θ r : ℝ}
    (hr : 0 ≤ r)
    (hlt : r < (T : ℝ) * exactlyOneSATDrift k hk)
    (hθ : 0 < θ)
    (hmargin :
      -Real.log θ ≤
        BernoulliCSPPathChernoff.linearCenter
          (exactlyOneSATParameters k hk) s₀ T - r) :
    StoppedCollapseWithFailureBound
      (μ := pathMeasure k hk N)
      (process k hk N s₀)
      T θ
      (countChernoffFailureBound k hk T r) := by
  simpa [
    pathMeasure,
    process,
    countChernoffFailureBound,
    exactlyOneSATParameters,
    exactlyOneSATDrift,
  ] using
    (exactlyOneSATWitness k hk).stoppedCollapseWithChernoffBound_of_linearMargin
      N hT hr (by simpa [exactlyOneSATDrift] using hlt) hθ hmargin

/-- Earlier threshold crossing gives a high-probability
hitting-time-before-horizon bound for exactly-one-SAT. -/
theorem hittingTimeBeforeHorizonWithChernoffBound_of_linearMargin
    (k : ℕ) (hk : 0 < k) (N : ℕ) {j T : ℕ} (hjT : j < T)
    (hj : j ≤ N + 1) {s₀ θ r : ℝ}
    (hr : 0 ≤ r)
    (hlt : r < (j : ℝ) * exactlyOneSATDrift k hk)
    (hmargin :
      -Real.log θ ≤
        BernoulliCSPPathChernoff.linearCenter
          (exactlyOneSATParameters k hk) s₀ j - r) :
    HittingTimeBeforeHorizonWithFailureBound
      (μ := pathMeasure k hk N)
      (process k hk N s₀)
      T θ
      (countChernoffFailureBound k hk j r) := by
  simpa [
    pathMeasure,
    process,
    countChernoffFailureBound,
    exactlyOneSATParameters,
    exactlyOneSATDrift,
  ] using
    (exactlyOneSATWitness k hk).hittingTimeBeforeHorizonWithChernoffBound_of_linearMargin
      N hjT hj hr (by simpa [exactlyOneSATDrift] using hlt) hmargin

end

end Survival.ExactlyOneSATChernoffCollapse
