import Mathlib.Data.Fintype.Basic
import Survival.CoarseTypicalNondecrease

/-!
Markov Repair / Failure Example
有限状態の Markov-style repair / failure 具体例

This module refines `ToyRandomWalk` by moving from arbitrary nonnegative
increments to a finite-state repair/failure vocabulary.

The state space has three modes:

* `failure` : structural damage is being paid as net action;
* `idle`    : no update;
* `repair`  : resources are being spent on repair.

We stop one layer short of constructing an actual Markov-chain measure from a
transition kernel. Instead, we formalize the finite-state path process itself
on an arbitrary probability space, together with a transition law recorded as
bookkeeping data. This is enough for the structural-persistence theorems in the
current Lean stack, whose monotonicity results only need the emitted
nonnegative total production.
-/

namespace Survival.MarkovRepairFailureExample

open MeasureTheory
open scoped BigOperators

open Survival.StochasticTotalProduction
open Survival.CoarseStochasticTotalProduction
open Survival.CoarseTypicalNondecrease

noncomputable section

variable {Ω : Type*} [MeasurableSpace Ω]
variable {μ : Measure Ω} [IsProbabilityMeasure μ]

/-- Finite repair/failure state space. -/
inductive RepairState where
  | failure
  | idle
  | repair
  deriving DecidableEq, Fintype, Repr

/-- A finite-state transition law.

The current theorems do not yet construct the corresponding Markov measure;
the law is recorded so that the example stays explicitly "Markov-style"
instead of being just an anonymous finite-state process. -/
structure TransitionLaw where
  prob : RepairState → RepairState → ℝ
  nonneg : ∀ s s', 0 ≤ prob s s'
  row_sum_one : ∀ s, Finset.sum Finset.univ (fun s' => prob s s') = 1

/-- A finite-state path process together with its intended transition law. -/
structure MarkovStyleStateProcess where
  stateRV : ℕ → Ω → RepairState
  law : TransitionLaw

/-- State-dependent net-action / cost emission. -/
structure Emission where
  netActionOf : RepairState → ℝ
  costOf : RepairState → ℝ
  total_nonneg : ∀ s, 0 ≤ netActionOf s + costOf s

/-- Canonical repair/failure emission:
failure contributes positive net action `a`,
idle contributes nothing,
repair contributes positive cost `c`. -/
def canonicalEmission (a c : ℝ) (ha : 0 ≤ a) (hc : 0 ≤ c) : Emission where
  netActionOf
    | .failure => a
    | .idle => 0
    | .repair => 0
  costOf
    | .failure => 0
    | .idle => 0
    | .repair => c
  total_nonneg := by
    intro s
    cases s <;> simp [ha, hc]

/-- The stochastic total-production step model generated by the finite-state
repair/failure process and a state-dependent emission map. -/
def stepModel
    (s₀ : ℝ)
    (P : MarkovStyleStateProcess (Ω := Ω))
    (E : Emission)
    (integrable_netAction :
      ∀ t, Integrable (fun ω => E.netActionOf (P.stateRV t ω)) μ)
    (integrable_cost :
      ∀ t, Integrable (fun ω => E.costOf (P.stateRV t ω)) μ) :
    StepModel (μ := μ) where
  initialRV := fun _ => s₀
  stepNetActionRV t := fun ω => E.netActionOf (P.stateRV t ω)
  stepCostRV t := fun ω => E.costOf (P.stateRV t ω)
  integrable_initial := integrable_const s₀
  integrable_stepNetAction := integrable_netAction
  integrable_stepCost := integrable_cost

theorem stepTotalProductionRV_eq_emission
    (s₀ : ℝ)
    (P : MarkovStyleStateProcess (Ω := Ω))
    (E : Emission)
    (hA : ∀ t, Integrable (fun ω => E.netActionOf (P.stateRV t ω)) μ)
    (hC : ∀ t, Integrable (fun ω => E.costOf (P.stateRV t ω)) μ)
    (t : ℕ) :
    stepTotalProductionRV (stepModel (μ := μ) s₀ P E hA hC) t =
      fun ω => E.netActionOf (P.stateRV t ω) + E.costOf (P.stateRV t ω) := by
  funext ω
  simp [stepTotalProductionRV, stepModel]

theorem canonical_stepTotalProductionRV
    (s₀ a c : ℝ)
    (ha : 0 ≤ a) (hc : 0 ≤ c)
    (P : MarkovStyleStateProcess (Ω := Ω))
    (hA : ∀ t, Integrable (fun ω => (canonicalEmission a c ha hc).netActionOf (P.stateRV t ω)) μ)
    (hC : ∀ t, Integrable (fun ω => (canonicalEmission a c ha hc).costOf (P.stateRV t ω)) μ)
    (t : ℕ) :
    stepTotalProductionRV
        (stepModel (μ := μ) s₀ P (canonicalEmission a c ha hc) hA hC) t =
      fun ω =>
        match P.stateRV t ω with
        | .failure => a
        | .idle => 0
        | .repair => c := by
  funext ω
  simp [stepTotalProductionRV, stepModel, canonicalEmission]
  cases P.stateRV t ω <;> simp

/-- Finite-state repair/failure emissions are resource-bounded whenever the
statewise emitted total production is pointwise nonnegative. -/
theorem ae_nonnegative_stepTotalProduction
    (s₀ : ℝ)
    (P : MarkovStyleStateProcess (Ω := Ω))
    (E : Emission)
    (hA : ∀ t, Integrable (fun ω => E.netActionOf (P.stateRV t ω)) μ)
    (hC : ∀ t, Integrable (fun ω => E.costOf (P.stateRV t ω)) μ) :
    AENonnegativeStepTotalProduction (μ := μ) (stepModel (μ := μ) s₀ P E hA hC) := by
  intro t
  refine Filter.Eventually.of_forall ?_
  intro ω
  rw [stepTotalProductionRV_eq_emission (μ := μ) s₀ P E hA hC t]
  exact E.total_nonneg (P.stateRV t ω)

/-- Therefore the expected cumulative total production is monotone. -/
theorem expectedCumulative_monotone
    (s₀ : ℝ)
    (P : MarkovStyleStateProcess (Ω := Ω))
    (E : Emission)
    (hA : ∀ t, Integrable (fun ω => E.netActionOf (P.stateRV t ω)) μ)
    (hC : ∀ t, Integrable (fun ω => E.costOf (P.stateRV t ω)) μ) :
    Monotone
      (stepModel (μ := μ) s₀ P E hA hC).toStochasticProcess.toExpectedProcess.expectedCumulative :=
  expectedCumulative_monotone_of_ae_nonnegative_stepTotalProduction
    (stepModel (μ := μ) s₀ P E hA hC)
    (ae_nonnegative_stepTotalProduction (μ := μ) s₀ P E hA hC)

/-- The coarse-grained typical nondecrease theorem applies directly to the
finite-state repair/failure model. -/
theorem coarse_expectedCumulative_monotone
    (s₀ : ℝ)
    (P : MarkovStyleStateProcess (Ω := Ω))
    (E : Emission)
    (hA : ∀ t, Integrable (fun ω => E.netActionOf (P.stateRV t ω)) μ)
    (hC : ∀ t, Integrable (fun ω => E.costOf (P.stateRV t ω)) μ)
    {Scoarse : StepModel (μ := μ)}
    (hcomp :
      CoarseStochasticCompatibility
        (μ := μ)
        (stepModel (μ := μ) s₀ P E hA hC)
        Scoarse) :
    Monotone Scoarse.toStochasticProcess.toExpectedProcess.expectedCumulative :=
  coarse_expectedCumulative_monotone_of_micro_nonnegative
    hcomp
    (ae_nonnegative_stepTotalProduction (μ := μ) s₀ P E hA hC)

end

end Survival.MarkovRepairFailureExample
